-- =============================================================================
-- BigQuery Schema Reference — stripe_mrr dataset
--
-- All tables and views are created automatically by etl/extract_load.py.
-- This file is documentation only — do not run it directly.
-- =============================================================================


-- =============================================================================
-- TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- sub_snapshots (SOURCE OF TRUTH FOR MRR)
--
-- Monthly point-in-time snapshots of every active subscription.
-- Generated by scripts/generate_data.py, loaded by etl/extract_load.py.
-- One row per customer per month. Cancelled customers are excluded.
-- mrr_cents = price_amount × screens
-- -----------------------------------------------------------------------------
-- month          STRING    -- "2025-08"
-- customer_id    STRING    -- "cus_abc123"
-- subscription_id STRING   -- "sub_xyz789"
-- plan           STRING    -- "free", "standard", "pro_plus", "engage", "enterprise"
-- price_id       STRING    -- "price_1ABC..."
-- price_amount   INTEGER   -- cents per screen per month (e.g., 1500 = $15)
-- screens        INTEGER   -- number of screens
-- mrr_cents      INTEGER   -- price_amount × screens (e.g., 18000 = $180)
-- status         STRING    -- "active" or "past_due"


-- =============================================================================
-- VIEWS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- mrr_monthly
--
-- Monthly MRR with customer counts. Derived from sub_snapshots.
-- -----------------------------------------------------------------------------
-- month                 STRING   -- "2025-08"
-- mrr_amount            FLOAT    -- total MRR in dollars
-- paying_customers      INTEGER  -- distinct customers with mrr_cents > 0
-- total_customers       INTEGER  -- all active customers including Free tier
-- active_subscriptions  INTEGER  -- distinct subscriptions
-- past_due_customers    INTEGER  -- distinct customers with status = 'past_due'
-- at_risk_mrr           FLOAT    -- MRR from past_due customers in dollars


-- -----------------------------------------------------------------------------
-- mrr_by_plan
--
-- MRR broken down by plan tier per month. Derived from sub_snapshots.
-- Plan key is mapped to display name (e.g., "pro_plus" → "Pro Plus").
-- -----------------------------------------------------------------------------
-- month       STRING  -- "2025-08"
-- plan_name   STRING  -- "Free", "Standard", "Pro Plus", "Engage", "Enterprise"
-- mrr_amount  FLOAT   -- MRR for this plan in dollars


-- -----------------------------------------------------------------------------
-- arppu_monthly
--
-- Average Revenue Per Paying User. Derived from mrr_monthly.
-- Formula: mrr_amount / paying_customers (returns 0 if no paying customers).
-- -----------------------------------------------------------------------------
-- month             STRING
-- mrr_amount        FLOAT
-- paying_customers  INTEGER
-- arppu             FLOAT


-- -----------------------------------------------------------------------------
-- customers_by_plan
--
-- Customer count per plan tier per month. Derived from sub_snapshots.
-- -----------------------------------------------------------------------------
-- month           STRING  -- "2025-08"
-- plan_name       STRING  -- "Free", "Standard", "Pro Plus", "Engage", "Enterprise"
-- customer_count  INTEGER


-- -----------------------------------------------------------------------------
-- churn_monthly
--
-- Monthly customer churn rate. Derived from mrr_monthly.
-- Formula: (prev_customers - total_customers) / prev_customers * 100
-- First month returns 0 (no previous month to compare).
-- -----------------------------------------------------------------------------
-- month            STRING   -- "2025-08"
-- total_customers  INTEGER  -- total customers this month
-- prev_customers   INTEGER  -- total customers previous month (via LAG)
-- churn_rate       FLOAT    -- churn rate as percentage